2025-05-28 00:14:25,941 -- INFO -- Start Glances 4.3.1
2025-05-28 00:14:25,941 -- INFO -- CPython 3.12.10 (/data/data/com.termux/files/usr/bin/python3.12) and psutil 5.9.8 detected
2025-05-28 00:14:25,952 -- INFO -- Read configuration file '/data/data/com.termux/files/usr/share/doc/glances/glances.conf'
2025-05-28 00:14:25,990 -- WARNING -- Missing Python Lib (No module named 'pydantic'), EventList will be skipping data validation
2025-05-28 00:14:26,017 -- INFO -- Start GlancesStandalone mode
2025-05-28 00:14:26,213 -- WARNING -- Error loading Docker deps Lib. Docker plugin is disabled (No module named 'docker')
2025-05-28 00:14:26,216 -- WARNING -- Error loading Podman deps Lib. Podman feature in the Containers plugin is disabled (No module named 'podman')
2025-05-28 00:14:26,222 -- CRITICAL -- Error while initializing the cpu plugin ([Errno 13] Permission denied: '/proc/stat')
2025-05-28 00:14:26,228 -- ERROR -- Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/stats.py", line 100, in _load_plugin
    plugin = import_module('glances.plugins.' + plugin_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/plugins/cpu/__init__.py", line 13, in <module>
    from glances.cpu_percent import cpu_percent
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/cpu_percent.py", line 161, in <module>
    cpu_percent = CpuPercent()
                  ^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/cpu_percent.py", line 65, in __init__
    self.cpu_percent = self._compute_cpu()
                       ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/cpu_percent.py", line 124, in _compute_cpu
    return psutil.cpu_percent(interval=0.0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/__init__.py", line 1816, in cpu_percent
    t1 = _last_cpu_times.get(tid) or cpu_times()
                                     ^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/__init__.py", line 1681, in cpu_times
    return _psplatform.cpu_times()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/_pslinux.py", line 620, in cpu_times
    set_scputimes_ntuple(procfs_path)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/_common.py", line 448, in wrapper
    raise raise_from(err, None)
          ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in raise_from
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/_common.py", line 446, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/_pslinux.py", line 274, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/_common.py", line 788, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/proc/stat'

2025-05-28 00:14:26,249 -- WARNING -- Missing Python Lib (No module named 'netifaces'), IP plugin is disabled
2025-05-28 00:14:26,249 -- WARNING -- Netifaces2 should be installed in your Python environment, IP plugin is disabled
2025-05-28 00:14:26,261 -- CRITICAL -- Error while initializing the network plugin ([Errno 13] Permission denied: '/proc/net/dev')
2025-05-28 00:14:26,264 -- ERROR -- Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/stats.py", line 102, in _load_plugin
    self._plugins[plugin_path] = plugin.PluginModel(args=args, config=config)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/plugins/network/__init__.py", line 101, in __init__
    self.update()
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/plugins/plugin/model.py", line 1141, in wrapper
    ret = fct(*args, **kw)
          ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/plugins/network/__init__.py", line 116, in update
    stats = self.update_local()
            ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/plugins/plugin/model.py", line 1191, in wrapper
    stats = fct(self, *args, **kw)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/plugins/network/__init__.py", line 138, in update_local
    net_io_counters = psutil.net_io_counters(pernic=True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/__init__.py", line 2166, in net_io_counters
    rawdict = _psplatform.net_io_counters()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/_pslinux.py", line 1068, in net_io_counters
    with open_text("%s/net/dev" % get_procfs_path()) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/_common.py", line 802, in open_text
    fobj = open(
           ^^^^^
PermissionError: [Errno 13] Permission denied: '/proc/net/dev'

2025-05-28 00:14:26,271 -- CRITICAL -- Error while initializing the percpu plugin ([Errno 13] Permission denied: '/proc/stat')
2025-05-28 00:14:26,273 -- ERROR -- Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/stats.py", line 100, in _load_plugin
    plugin = import_module('glances.plugins.' + plugin_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/plugins/percpu/__init__.py", line 11, in <module>
    from glances.cpu_percent import cpu_percent
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/cpu_percent.py", line 161, in <module>
    cpu_percent = CpuPercent()
                  ^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/cpu_percent.py", line 65, in __init__
    self.cpu_percent = self._compute_cpu()
                       ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/cpu_percent.py", line 124, in _compute_cpu
    return psutil.cpu_percent(interval=0.0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/__init__.py", line 1816, in cpu_percent
    t1 = _last_cpu_times.get(tid) or cpu_times()
                                     ^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/__init__.py", line 1681, in cpu_times
    return _psplatform.cpu_times()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/_pslinux.py", line 620, in cpu_times
    set_scputimes_ntuple(procfs_path)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/_common.py", line 448, in wrapper
    raise raise_from(err, None)
          ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in raise_from
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/_common.py", line 446, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/_pslinux.py", line 274, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/_common.py", line 788, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/proc/stat'

2025-05-28 00:14:26,305 -- CRITICAL -- Error while initializing the quicklook plugin ([Errno 13] Permission denied: '/proc/stat')
2025-05-28 00:14:26,307 -- ERROR -- Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/stats.py", line 100, in _load_plugin
    plugin = import_module('glances.plugins.' + plugin_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/plugins/quicklook/__init__.py", line 13, in <module>
    from glances.cpu_percent import cpu_percent
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/cpu_percent.py", line 161, in <module>
    cpu_percent = CpuPercent()
                  ^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/cpu_percent.py", line 65, in __init__
    self.cpu_percent = self._compute_cpu()
                       ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/cpu_percent.py", line 124, in _compute_cpu
    return psutil.cpu_percent(interval=0.0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/__init__.py", line 1816, in cpu_percent
    t1 = _last_cpu_times.get(tid) or cpu_times()
                                     ^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/__init__.py", line 1681, in cpu_times
    return _psplatform.cpu_times()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/_pslinux.py", line 620, in cpu_times
    set_scputimes_ntuple(procfs_path)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/_common.py", line 448, in wrapper
    raise raise_from(err, None)
          ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in raise_from
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/_common.py", line 446, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/_pslinux.py", line 274, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/_common.py", line 788, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/proc/stat'

2025-05-28 00:14:26,309 -- WARNING -- Missing Python Lib (No module named 'pymdstat'), Raid plugin is disabled
2025-05-28 00:14:26,324 -- ERROR -- Cannot grab battery status [Errno 13] Permission denied: '/sys/class/power_supply'.
2025-05-28 00:14:26,361 -- WARNING -- Missing Python Lib (No module named 'pySMART'), HDD Smart plugin is disabled
2025-05-28 00:14:26,365 -- CRITICAL -- Error while initializing the uptime plugin ([Errno 13] Permission denied: '/proc/stat')
2025-05-28 00:14:26,367 -- ERROR -- Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/stats.py", line 102, in _load_plugin
    self._plugins[plugin_path] = plugin.PluginModel(args=args, config=config)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/glances/plugins/uptime/__init__.py", line 38, in __init__
    self.uptime = datetime.now() - datetime.fromtimestamp(psutil.boot_time())
                                                          ^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/__init__.py", line 2364, in boot_time
    return _psplatform.boot_time()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/_pslinux.py", line 1633, in boot_time
    with open_binary(path) as f:
         ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/psutil/_common.py", line 788, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/proc/stat'

